version: 0.0.{build}
os:
  - Visual Studio 2013
clone_depth: 1
skip_tags: true
clone_folder: c:\dcmqi
configuration:
  - Release
platform:
  - x64
before_build:
  - npm install jsonlint -g
  - npm install ajv-cli -g
  - cmd: cmake --version
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/zlib/releases/download/zlib-dcmqi-1.2.3-VS12-Win64-Release/zlib-dcmqi.zip", "C:\zlib-dcmqi.zip")
  - cmd: 7z x C:\zlib-dcmqi.zip -oC:\zlib-install
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/QIICR/dcmtk/releases/download/DCMTK-dcmqi-3.6.1_20160812-VS12-Win64-Release-v0.0.4/DCMTK-dcmqi.zip", "C:\DCMTK-dcmqi.zip")
  - cmd: 7z x C:\DCMTK-dcmqi.zip -oC:\DCMTK-install
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/ITK-dcmqi/releases/download/ITK-dcmqi-VS12-Win64-Release-v0.0.23/ITK-dcmqi.zip", "C:\ITK-dcmqi.zip")
  - cmd: 7z x C:\ITK-dcmqi.zip -oC:\ITK-install
  - cmd: cd c:\
  - cmd: git clone https://github.com/fedorov/SlicerExecutionModel.git SlicerExecutionModel
  - cmd: cd c:\SlicerExecutionModel
  - cmd: git checkout dcmqi-311eff
  - ps: $client = new-object System.Net.WebClient;$client.DownloadFile("https://github.com/fedorov/SlicerExecutionModel/releases/download/SlicerExecutionModel-dcmqi-VS12-Win64-Release-v0.0.5/SlicerExecutionModel-dcmqi.zip", "C:\SlicerExecutionModel-dcmqi.zip")
  - cmd: 7z x C:\SlicerExecutionModel-dcmqi.zip -oC:\SlicerExecutionModel\SlicerExecutionModel-build
  - cmd: mkdir c:\dcmqi\dcmqi-build
  - cmd: cd c:\dcmqi\dcmqi-build
  - cmd: cmake -G "Visual Studio 12 2013 Win64" -DCMAKE_BUILD_TYPE:STRING=Release -DITK_DIR:PATH=C:\ITK-install -DSlicerExecutionModel_DIR:PATH=C:\SlicerExecutionModel\SlicerExecutionModel-build -DDCMTK_DIR:PATH=C:\DCMTK-install\cmake -DZLIB_ROOT:PATH=c:\zlib-install -DZLIB_INCLUDE_DIR:PATH=c:\zlib-install\include -DZLIB_LIBRARY:FILEPATH=c:\zlib-install\lib\zlib.lib c:\dcmqi
  - cmd: dir
build_script:
  - cmd: type DCMQI.sln
  - cmd: msbuild DCMQI.sln /m
after_build:
  - cmd: cd c:\dcmqi\dcmqi-build\dcmqi-build
  - cmd: set PATH=%PATH%;c:\DCMTK-install\lib;c:\ITK-install\lib;c:\zlib-install\lib && ctest -R Release -D ExperimentalTest --no-compress-output
artifacts:
  - path: dcmqi-build
    name: dcmqi
    type: zip
cache:
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
